default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  database: allergic_project_api_development

test:
  <<: *default
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  database: allergic_project_api_test

production:
  <<: *default
  database: allergic_project_api_production
  username: allergic_project_admin
  password: <%= ENV['ALLERGIC_PROJECT_API_DATABASE_PASSWORD'] %>
